# Generated by Django 5.2 on 2025-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tech", "技術部"),
                    ("sales", "業務部"),
                    ("finance", "財務部"),
                    ("marketing", "行銷部"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
