# Generated by Django 5.2.4 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
