# Generated by Django 5.2.4 on 2025-07-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresettoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={},
        ),
    ]
