# Generated by Django 5.2 on 2025-05-02 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色代碼')),
                ('name', models.CharField(max_length=100, verbose_name='角色名稱')),
                ('role_name', models.CharField(max_length=100, verbose_name='角色英文名稱')),
                ('role_zh', models.CharField(max_length=100, verbose_name='角色中文名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('category', models.CharField(max_length=50, verbose_name='分類')),
                ('level', models.IntegerField(default=1, verbose_name='層級')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['category', 'level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='權限代碼')),
                ('name', models.CharField(max_length=100, verbose_name='權限名稱')),
                ('category', models.CharField(max_length=50, verbose_name='分類')),
                ('module', models.CharField(max_length=50, verbose_name='模組')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('resource', models.CharField(max_length=50, verbose_name='資源')),
                ('level', models.IntegerField(default=1, verbose_name='層級')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('api_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='API URL')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP 方法')),
                ('function_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='功能中文名稱')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.permission', verbose_name='父權限')),
            ],
            options={
                'verbose_name': '權限',
                'verbose_name_plural': '權限',
                'ordering': ['module', 'level', 'code'],
                'unique_together': {('module', 'action', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission', verbose_name='權限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色權限',
                'verbose_name_plural': '角色權限',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='rbac.RolePermission', to='rbac.permission', verbose_name='權限'),
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('child_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='rbac.role', verbose_name='子角色')),
                ('parent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.role', verbose_name='父角色')),
            ],
            options={
                'verbose_name': '角色階層',
                'verbose_name_plural': '角色階層',
                'ordering': ['parent_role', 'child_role'],
                'unique_together': {('parent_role', 'child_role')},
            },
        ),
    ]
