# Generated by Django 5.2 on 2025-06-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_add_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='special_conditions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='特殊條件'),
        ),
        migrations.AddField(
            model_name='role',
            name='stage',
            field=models.CharField(choices=[('frontstage', '前台'), ('backstage', '後台')], default='backstage', max_length=20, verbose_name='前台/後台'),
        ),
    ]
