# Generated by Django 5.2.4 on 2025-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_answerlike_questionlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
